railsApp/config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  namespace :web do
    get 'photos/index'
    get 'photos/show'
    get 'events/calandar'
    get 'events/show'
  end

  get 'home/index'
  resources :photos
  resources :albums
  resources :events
  resources :pages

  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users
  resources :sections
  resources :sponsors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
end

railsApp/app/models/section.rb
class Section < ApplicationRecord
    has_many :pages
	validates :title, :location, presence: true
end

railsApp/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[ show edit update destroy ]

  # GET /sections or /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1 or /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections or /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to section_url(@section), notice: "Section was successfully created." }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1 or /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to section_url(@section), notice: "Section was successfully updated." }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1 or /sections/1.json
  def destroy
    @section.destroy

    respond_to do |format|
      format.html { redirect_to sections_url, notice: "Section was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:location, :position, :title, :visible)
    end
end

railsApp/app/helpers/sections_helper.rb
module SectionsHelper
end

railsApp/app/views/sections/_form.html.erb
<%= form_with(model: section) do |form| %>
  <% if section.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :visible, style: "display: block" %>
    <%= form.check_box :visible %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

railsApp/app/views/sections/_section.html.erb
<div id="<%= dom_id section %>">
  <p>
    <strong>Location:</strong>
    <%= section.location %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= section.position %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= section.title %>
  </p>

  <p>
    <strong>Visible:</strong>
    <%= section.visible %>
  </p>

</div>

railsApp/app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render "form", section: @section %>

<br>

<div>
  <%= link_to "Show this section", @section %> |
  <%= link_to "Back to sections", sections_path %>
</div>

railsApp/app/views/sections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sections</h1>

<div id="sections">
  <% @sections.each do |section| %>
    <%= render section %>
    <p>
      <%= link_to "Show this section", section %>
    </p>
  <% end %>
</div>

<%= link_to "New section", new_section_path %>

railsApp/app/views/sections/new.html.erb
<h1>New section</h1>

<%= render "form", section: @section %>

<br>

<div>
  <%= link_to "Back to sections", sections_path %>
</div>

railsApp/app/views/sections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @section %>

<% Page.all.each do |p| %>
  <%= p.title %>
<% end %>
<div>
  <%= link_to "Edit this section", edit_section_path(@section) %> |
  <%= link_to "Back to sections", sections_path %>

  <%= button_to "Destroy this section", @section, method: :delete %>
</div>