railsApp/config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  namespace :web do
    get 'photos/index'
    get 'photos/show'
    get 'events/calandar'
    get 'events/show'
  end

  get 'home/index'
  resources :photos
  resources :albums
  resources :events
  resources :pages

  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users
  resources :sections
  resources :sponsors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
end

railsApp/app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :photo
    validates :title, :eventstart, :eventend, presence: true
    validate :countFeatured

    def start_time
        eventstart
    end

    def countFeatured
        if Event.where(featured: true).length >= 4
            errors.add(:featured, "can't be greater than 4")
        end
    end
end

railsApp/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :allday, :eventstart, :eventend, :occurence, :details, :featured, :photo)
    end
end

railsApp/app/controllers/web/events_controller.rb
class Web::EventsController < ApplicationController
  def calandar
    # Scope your query to the dates being shown:
    start_date = params.fetch(:start_date, Date.today).to_date
    @events = Event.where(eventstart: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
  end

  def show
  end
end

railsApp/app/helpers/events_helper.rb
module EventsHelper
end

railsApp/app/helpers/web/events_helper.rb
module Web::EventsHelper
end

railsApp/app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Title:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Allday:</strong>
    <%= event.allday %>
  </p>

  <p>
    <strong>Eventstart:</strong>
    <%= event.eventstart %>
  </p>

  <p>
    <strong>Eventend:</strong>
    <%= event.eventend %>
  </p>

  <p>
    <strong>Occurence:</strong>
    <%= event.occurence %>
  </p>

  <p>
    <strong>Details:</strong>
    <%= event.details %>
  </p>

  <p>
    <strong>Features:</strong>
    <%= event.featured %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= image_tag(event.photo, width: "50%") %>
  </p>

</div>

railsApp/app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :allday, style: "display: block" %>
    <%= form.check_box :allday %>
  </div>

  <div>
    <%= form.label :eventstart, style: "display: block" %>
    <%= form.datetime_field :eventstart %>
  </div>

  <div>
    <%= form.label :eventend, style: "display: block" %>
    <%= form.datetime_field :eventend %>
  </div>

  <div>
    <%= form.label :occurence, style: "display: block" %>
    <%= form.number_field :occurence %>
  </div>

  <div>
    <%= form.label :details, style: "display: block" %>
    <%= form.text_area :details %>
  </div>

  <div>
    <%= form.label :featured, style: "display: block" %>
    <%= form.check_box :featured %>
  </div>

  <div>
    <%= form.file_field :photo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

railsApp/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

railsApp/app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="events" class = "row">
  <% @events.each do |event| %>
    <div class="card col-lg-4 mx-auto my-3" style="width: 18rem;">
      <div class="card-body">
        <%= image_tag(event.photo, width: "100%") %>
        <h5 class="card-title"><%= event.title %></h5>
        <p class="card-text">Details: <%= event.details %></p>
        <p class = "card-text">Start Date: <%= event.eventstart %></p>
        <p class = "card-text">End Date: <%= event.eventend %></p>
        <p class = "card-text"> Featured: <%= event.featured %></p>
        <p class = "card-text"> Occurence: <%= event.occurence %></p>

        <p>
          <%= link_to "Show this event", event %>
        </p>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "New event", new_event_path %>

railsApp/app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

railsApp/app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<div>
  <%= link_to "Edit this event", edit_event_path(@event) %> |
  <%= link_to "Back to events", events_path %>

  <%= button_to "Destroy this event", @event, method: :delete %>
</div>