railsApp/config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  namespace :web do
    get 'photos/index'
    get 'photos/show'
    get 'events/calandar'
    get 'events/show'
  end

  get 'home/index'
  resources :photos
  resources :albums
  resources :events
  resources :pages

  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users
  resources :sections
  resources :sponsors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
end

railsApp/app/models/album.rb
class Album < ApplicationRecord
    has_many :photos
    validates :title, :description, presence: true
end

railsApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

railsApp/app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :photo
    validates :title, :eventstart, :eventend, presence: true
    validate :countFeatured

    def start_time
        eventstart
    end

    def countFeatured
        if Event.where(featured: true).length >= 4
            errors.add(:featured, "can't be greater than 4")
        end
    end
end

railsApp/app/models/page.rb
class Page < ApplicationRecord
    belongs_to :section
	validates :title, presence: true
	has_one_attached :doc
end

railsApp/app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :album
    has_one_attached :image 
end

railsApp/app/models/section.rb
class Section < ApplicationRecord
    has_many :pages
	validates :title, :location, presence: true
end

railsApp/app/models/sponsor.rb
class Sponsor < ApplicationRecord
    has_one_attached :image
    validates :title, presence: true
end

railsApp/app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  
  has_and_belongs_to_many :roles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

railsApp/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

railsApp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

railsApp/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:title, :section_id, :position, :page_type, :destination, :visible, :content)
    end
end

railsApp/app/helpers/admin_helper.rb
module AdminHelper
end

railsApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

railsApp/app/helpers/application_helper.rb
module ApplicationHelper
end

railsApp/app/helpers/events_helper.rb
module EventsHelper
end

railsApp/app/helpers/home_helper.rb
module HomeHelper
end

railsApp/app/helpers/pages_helper.rb
module PagesHelper
end

railsApp/app/helpers/photos_helper.rb
module PhotosHelper
end

railsApp/app/helpers/sections_helper.rb
module SectionsHelper
end

railsApp/app/helpers/sponsors_helper.rb
module SponsorsHelper
end

railsApp/app/views/admin/index.html.erb
<h1>Admin</h1>
<div class = "row">

    <div class="card col-lg-6 mx-auto my-3" style="width: 18rem;">
      <div class="card-body">
        <div>
            <%= link_to "albums", albums_path(@albums) %>
        </div>
      </div>
    </div>

    <div class="card col-lg-6 mx-auto my-3" style="width: 18rem;">
      <div class="card-body text-center">
        <div>
            <%= link_to "events", events_path(@events) %>
        </div>
      </div>
    </div>

    <div class="card col-lg-6 mx-auto my-3" style="width: 18rem;">
      <div class="card-body">
        <div>
            <%= link_to "pages", pages_path(@pages) %>
        </div>
      </div>
    </div>

    <div class="card col-lg-6 mx-auto my-3" style="width: 18rem;">
      <div class="card-body">
        <div>
            <%= link_to "photos", photos_path(@photos) %>
        </div>
      </div>
    </div>

    <div class="card col-lg-6 mx-auto my-3" style="width: 18rem;">
      <div class="card-body">
        <div>
            <%= link_to "sections", sections_path(@sections) %>
        </div>
      </div>
    </div>
</div>

railsApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <nav class="navbar red">
      <div class="container-fluid">
        <span class="navbar-brand mb-0 h2 fw-bold fs-2 p-4 text-light">HARMONY CLUB OF WORCESTER</span>

        <button class="blue navbar-toggler mx-5" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
          <label class = "text-light">Menu</label>
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>

    <div class="collapse" id="navbarToggleExternalContent">
      <div class="red p-4">
          <h2> <%= link_to "Home", home_index_path(@home), class: "text-light p-3" %> </h2>
          <h2> 
            <div>
              <% Section.all.each do |s| %>
                <button class="red dropdown-toggle text-light" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= s.title %>
                </button> 
                <div>
                  <ul class="dropdown-menu">
                    <% Page.all.each do |p| %>
                      <div class = "p-2"> <%= link_to p.title, page_path(id: p.id) %> </div>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
          </h2>
          <h2> <%= link_to "Photos", photos_path(@photos), class: "text-light p-3" %> </h2>
          <h2> <%= link_to "sponsors", sponsors_path(@sponsors), class: "text-light p-3" %> </h2>
          <h2> <%= link_to "Albums", albums_path(@albums), class: "text-light p-3" %> </h2>
          <h2> <%= link_to "Calendar", web_events_calandar_path(@calendar), class: "text-light p-3" %> </h2>
          <% if current_user %>
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
          <% else %>
            <%= link_to "Sign In", users_path, class: "nav-link" %>
          <% end %>
      </div>
    </div>

    <div class = "bg-light mx-5 text-center vh-100">
      <%= yield %>
    </div>
 
  <div class = "red text-light text-center">
    <p>Harmony Club of Worcester | 2022 </p>
    <hr></hr>
  </div>
</body>
</html>

railsApp/app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div data-controller = "page">
    <%= form.label :page_type, style: "display: block" %>
    <%= form.select :page_type, ["Basic Page", "External URL", "Internal URL", "PDF"], {}, data: {action: "change->page#typeChange","page-target": "title"}  %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class = "allContent">
    <%= form.label :section_id, style: "display: block" %>
    <%= form.select :section_id, options_from_collection_for_select(Section.all, 'id', 'title') %>
  </div>

  <div class = "allContent">
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div id = "destination">
    <%= form.label :destination, style: "display: block" %>
    <%= form.text_field :destination %>
  </div>

  <div class = "allContent">
    <%= form.label :visible, style: "display: block" %>
    <%= form.check_box :visible %>
  </div>

  <div id = "content" class = "allContent">
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div id = "type1">
    
  </div>

  <div id = "type2">

  </div>

  <div id = "type3">

  </div>

  <div id = "type4">

  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

railsApp/app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <p>
    <strong>Title:</strong>
    <%= page.title %>
  </p>

  <p>
    <strong>Section:</strong>
    <%= page.section_id %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= page.position %>
  </p>

  <p>
    <strong>Page type:</strong>
    <%= page.page_type %>
  </p>

  <p>
    <strong>Destination:</strong>
    <%= link_to page.title, page.destination, :target => "_blank" %>
  </p>

  <p>
    <strong>Visible:</strong>
    <%= page.visible %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= page.content %>
  </p>

</div>

railsApp/app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

railsApp/app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pages</h1>

<div id="pages" class = "row">
  <% @pages.each do |page| %>
    <div class="card col-lg-4 mx-auto my-3" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= page.title %></h5>
        <p class="card-text">Position: <%= page.position %></p>
        <p class = "card-text">Page Type: <%= page.page_type %></p>
        <p class = "card-text">Destination: <%= link_to page.title, page.destination, :target => "_blank" %></p>
        <p class = "card-text"> Visible: <%= page.visible %></p>
        <p class = "card-text"> Content: <%= page.content %></p>

        <p>
          <%= link_to "Show this page", page %>
        </p>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "New page", new_page_path %>

railsApp/app/views/pages/new.html.erb
<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

railsApp/app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>